import 'package:almohsen_s_hotel_s/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_hotel_s/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_hotel_s/widgets/app_bar/appbar_title.dart';import 'package:almohsen_s_hotel_s/widgets/app_bar/appbar_trailing_image.dart';import 'package:almohsen_s_hotel_s/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_hotel_s/core/app_export.dart';import 'controller/confirm_payment_controller.dart';class ConfirmPaymentScreen extends GetWidget<ConfirmPaymentController> {const ConfirmPaymentScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 23.v), child: Column(children: [_buildResortDetails(), SizedBox(height: 28.v), _buildBookingDetails(), SizedBox(height: 28.v), _buildPrice(), SizedBox(height: 28.v), _buildPaymentMethod(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildConfirmPayment())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 56.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 17.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "lbl_payment".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgTelevision, margin: EdgeInsets.fromLTRB(24.h, 10.v, 24.h, 17.v))]); } 
/// Section Widget
Widget _buildResortDetails() { return Container(padding: EdgeInsets.symmetric(vertical: 20.v), decoration: AppDecoration.outlineBlackC.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [SizedBox(width: 253.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRectangle42, height: 100.adaptSize, width: 100.adaptSize, radius: BorderRadius.circular(16.h)), Padding(padding: EdgeInsets.only(bottom: 9.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_bulgari_resort".tr, style: theme.textTheme.titleLarge), SizedBox(height: 15.v), Text("lbl_paris_france".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 12.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgSignalYellowA700, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_4_8".tr, style: CustomTextStyles.titleSmallPrimary)), Padding(padding: EdgeInsets.only(left: 8.h, top: 1.v), child: Text("lbl_4_378_reviews".tr, style: theme.textTheme.bodySmall))])]))])), Padding(padding: EdgeInsets.only(top: 9.v, bottom: 6.v), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Text("lbl_27".tr, style: CustomTextStyles.headlineSmallPrimary), SizedBox(height: 2.v), Text("lbl_night".tr, style: theme.textTheme.labelMedium), SizedBox(height: 16.v), CustomImageView(imagePath: ImageConstant.imgBookmarkPrimary, height: 24.adaptSize, width: 24.adaptSize)]))])); } 
/// Section Widget
Widget _buildBookingDetails() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 21.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 5.v), _buildAutoLayoutHorizontal(checkoutText: "lbl_check_in".tr, dateText: "msg_december_16_2024".tr), SizedBox(height: 20.v), _buildAutoLayoutHorizontal(checkoutText: "lbl_check_out".tr, dateText: "msg_december_20_2024".tr), SizedBox(height: 19.v), _buildAutoLayoutHorizontal(checkoutText: "lbl_guest".tr, dateText: "lbl_3".tr)])); } 
/// Section Widget
Widget _buildPrice() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 21.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 5.v), _buildAutoLayoutHorizontal(checkoutText: "lbl_5_nights".tr, dateText: "lbl_435_00".tr), SizedBox(height: 20.v), _buildAutoLayoutHorizontal(checkoutText: "msg_taxes_fees_10".tr, dateText: "lbl_44_50".tr), SizedBox(height: 17.v), Divider(), SizedBox(height: 21.v), _buildAutoLayoutHorizontal(checkoutText: "lbl_total".tr, dateText: "lbl_479_50".tr)])); } 
/// Section Widget
Widget _buildPaymentMethod() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 26.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 185.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgImage27x44, height: 27.v, width: 44.h, radius: BorderRadius.circular(4.h)), Padding(padding: EdgeInsets.symmetric(vertical: 2.v), child: Text("msg".tr, style: theme.textTheme.titleMedium))])), GestureDetector(onTap: () {onTapTxtChange();}, child: Padding(padding: EdgeInsets.only(top: 5.v), child: Text("lbl_change".tr, style: CustomTextStyles.titleMediumPrimarySemiBold)))])); } 
/// Section Widget
Widget _buildConfirmPayment() { return CustomElevatedButton(text: "lbl_confirm_payment".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 49.v)); } 
/// Common widget
Widget _buildAutoLayoutHorizontal({required String checkoutText, required String dateText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(checkoutText, style: CustomTextStyles.titleMediumOnPrimaryContainer.copyWith(color: theme.colorScheme.onPrimaryContainer))), Text(dateText, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.whiteA700))]); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
/// Navigates to the cardAddedScreen when the action is triggered.
onTapTxtChange() { Get.toNamed(AppRoutes.cardAddedScreen, ); } 
 }
