import 'package:almohsen_s_hotel_s/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_hotel_s/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_hotel_s/widgets/app_bar/appbar_title.dart';import 'package:almohsen_s_hotel_s/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_hotel_s/core/app_export.dart';import 'controller/forgot_password_controller.dart';class ForgotPasswordScreen extends GetWidget<ForgotPasswordController> {const ForgotPasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 39.v), child: Column(children: [SizedBox(height: 16.v), CustomImageView(imagePath: ImageConstant.imgImage, height: 240.adaptSize, width: 240.adaptSize), SizedBox(height: 41.v), Align(alignment: Alignment.centerLeft, child: Container(width: 355.h, margin: EdgeInsets.only(right: 24.h), child: Text("msg_select_which_contact".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyLarge!.copyWith(height: 1.50)))), SizedBox(height: 18.v), _buildUserRow(), SizedBox(height: 24.v), _buildCheckmarkRow()])), bottomNavigationBar: _buildContinueButton())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 16.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "lbl_forgot_password".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildUserRow() { return Container(padding: EdgeInsets.all(21.h), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(children: [Container(height: 80.adaptSize, width: 80.adaptSize, padding: EdgeInsets.all(26.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgUser, height: 26.adaptSize, width: 26.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 20.h, top: 15.v, bottom: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_via_sms".tr, style: CustomTextStyles.titleSmallGray400), SizedBox(height: 11.v), Text("lbl_1_111_99".tr, style: CustomTextStyles.titleMedium16)]))])); } 
/// Section Widget
Widget _buildCheckmarkRow() { return Container(padding: EdgeInsets.all(23.h), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(children: [Container(height: 80.adaptSize, width: 80.adaptSize, padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 28.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgCheckmarkPrimary, height: 24.v, width: 26.h, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 20.h, top: 15.v, bottom: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_via_email".tr, style: CustomTextStyles.titleSmallGray400), SizedBox(height: 12.v), Text("lbl_user_domain_com".tr, style: CustomTextStyles.titleMedium16)]))])); } 
/// Section Widget
Widget _buildContinueButton() { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 49.v), onPressed: () {onTapContinueButton();}); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
/// Navigates to the forgotPasswordTypeOtpScreen when the action is triggered.
onTapContinueButton() { Get.toNamed(AppRoutes.forgotPasswordTypeOtpScreen, ); } 
 }
