import 'package:almohsen_s_hotel_s/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_hotel_s/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_hotel_s/widgets/app_bar/appbar_title.dart';import 'package:almohsen_s_hotel_s/widgets/app_bar/appbar_trailing_image.dart';import 'package:almohsen_s_hotel_s/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:almohsen_s_hotel_s/widgets/custom_search_view.dart';import 'package:almohsen_s_hotel_s/presentation/home_screen_page/home_screen_page.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_hotel_s/core/app_export.dart';import 'controller/home_screen_tab_container_controller.dart';import 'models/home_screen_tab_container_model.dart';
// ignore_for_file: must_be_immutable
class HomeScreenTabContainerPage extends StatelessWidget {HomeScreenTabContainerPage({Key? key}) : super(key: key);

HomeScreenTabContainerController controller = Get.put(HomeScreenTabContainerController(HomeScreenTabContainerModel().obs));

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 25.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("msg_hello_daniel".tr, style: theme.textTheme.headlineLarge))), SizedBox(height: 23.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: CustomSearchView(controller: controller.searchController, hintText: "lbl_search".tr)), SizedBox(height: 31.v), _buildTabview(), SizedBox(height: 1312.v, child: TabBarView(controller: controller.tabviewController, children: [HomeScreenPage(), HomeScreenPage(), HomeScreenPage()]))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 50.v, leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgFloatingIcon, margin: EdgeInsets.only(left: 24.h, top: 9.v, bottom: 9.v)), title: AppbarTitle(text: "lbl_comfort".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgIcons, margin: EdgeInsets.only(left: 24.h, top: 11.v, right: 11.h), onTap: () {onTapIcons();}), AppbarTrailingIconbutton(imagePath: ImageConstant.imgSettingsWhiteA700, margin: EdgeInsets.only(left: 20.h, top: 11.v, right: 35.h))]); } 
/// Section Widget
Widget _buildTabview() { return Container(height: 38.v, width: 376.h, child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.whiteA700, labelStyle: TextStyle(fontSize: 16.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w600), unselectedLabelColor: theme.colorScheme.primary, unselectedLabelStyle: TextStyle(fontSize: 16.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w600), indicator: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(19.h)), tabs: [Tab(child: Text("lbl_recommended".tr)), Tab(child: Text("lbl_popular".tr)), Tab(child: Text("lbl_trending".tr))])); } 
/// Navigates to the notificationsScreen when the action is triggered.
onTapIcons() { Get.toNamed(AppRoutes.notificationsScreen, ); } 
 }
